### ISSUE TITLE
Be careful with using exact naming conventions as Apple

### ISSUE THREAD

**Issue by LeoNatan** [timonus/UIImageHEIC#2]
Hello,

Cool library!

Be careful with using exact naming conventions as Apple. It is not out of the question that Apple could name a function `UIImageHEICRepresentation` in the future. At best, there could be a symbol collision or at worst, undefined behavior. 

I understand the want to have a similarly named symbols, even if for completionist reasons only, but the risks are not worth it.

**Comment by timonus** [comment]
I actually prefixed it with tj_ this morning because of this, great suggestion.
