### ISSUE TITLE
When does tj_UIImageHEICRepresentation.length return 0?

### ISSUE THREAD

**Issue by enjoiful** [timonus/UIImageHEIC#3]
Does imageData.length return 0 if HEIC is not supported?  When/why would you fallback to JPEG representation?

NSData *imageData = tj_UIImageHEICRepresentation(image, 0.8);
if (imageData.length == 0) {
    imageData = UIImageJPEGRepresentation(image, 0.8);
}

Awesome project. Thanks!

**Comment by enjoiful** [comment]
Per the readme, this occurs on unsupported devices (specifically, devices that have A9 processor and below). error: "findWriterForType:140: unsupported file format 'public.heic'" 

I'm getting a UIImage from the camera picker, and would like to save that on my server as a heif file on any device with an A9 chip or above.  Thoughts on how to do that?

Sorry if this isn't the best forum for that question.  Cheers for any help or ideas.

**Comment by enjoiful** [comment]
Sorry for the noise. Looking into this more, heif creation on devices A9 and below is not possible.  iOS11 on A9 devices does not allow you to create heif images.

**Comment by enjoiful** [comment]
It looks like HEIF creation is possible natively on all devices if they run iOS11.  Below app proves that it's being done.

Any idea how we might be able to achieve this?

https://itunes.apple.com/us/app/half/id1288721004

**Comment by timonus** [comment]
@enjoiful not sure. According to Apple only devices with the A10 and above should be able to create HEIC images. Perhaps that app is either lying about its capabilities or using a third party-library to do software encoding.

**Comment by devancorona** [comment]
@timonus I've been struggling to get HEIF/HEIC conversions working on an A9 processor and stumbled upon your library. 

I'm curious, where did you see that "only devices with the A10 and above should be able to create HEIC images"? 

I've been following along the notes from WWDC on HEIF and HEVC formats and it seems to indicate HEIF is supported on all iOS 11 devices; slide #260 here: https://devstreaming-cdn.apple.com/videos/wwdc/2017/511tj33587vdhds/511/511_working_with_heif_and_hevc.pdf

Any chance you can point me toward your source of information on this only being compatible with A10s? I would be super grateful.

**Comment by timonus** [comment]
@roco5754 HEIC _de_code is available on all iOS 11 devices

![screen shot 2017-10-31 at 5 51 30 pm](https://user-images.githubusercontent.com/522951/32255315-31355344-be64-11e7-83e8-90966b5b8e87.png)


But _en_coding only works on the A10 or above.

![screen shot 2017-10-31 at 5 51 38 pm](https://user-images.githubusercontent.com/522951/32255321-41cb582a-be64-11e7-941a-1b9d93356e59.png)

**Comment by devancorona** [comment]
Thanks! I got lost in the depths and couldn't find my way out.

**Comment by enjoiful** [comment]
For what it's worth, it's absolutely possible to perform HEIC encoding on A9 devices, but Apple does not natively support it per the above comments. An outside library must be used, something like this:  https://github.com/nokiatech/heif

If anyone pushes forward with this publicly, would love an update in this thread.

**Comment by devancorona** [comment]
Does anyone know how long the encoding takes using the iOS sdk on an A10? If it takes a while on the A10 with hardware encoding, it might not be worth it on an A9 with software encode.

**Comment by enjoiful** [comment]
I'm seeing about 100ms for the conversion using this library.  A 1s conversion would be totally acceptable for many use cases.
